/**
 * config/web3.js — Web3.js Setup for the Backend
 *
 * This file does THREE things:
 *  1. Creates a Web3 instance connected to Ganache (local blockchain)
 *  2. Loads the compiled contract ABI from Grievance.json (generated by Truffle)
 *  3. Creates a contract instance that backend routes can call like a normal JS object
 *
 * IMPORTANT: You must run `truffle compile` and `truffle migrate` BEFORE starting
 * the backend — otherwise Grievance.json won't exist and this file will crash.
 */

const Web3 = require("web3");
const path = require("path");
const fs   = require("fs");

// ─────────────────────────────────────────────
// STEP 1 — Connect Web3 to Ganache
// ─────────────────────────────────────────────

// This creates a Web3 instance that talks to Ganache at localhost:7545
const web3 = new Web3(process.env.GANACHE_URL || "http://127.0.0.1:7545");

// ─────────────────────────────────────────────
// STEP 2 — Load the compiled contract JSON
// ─────────────────────────────────────────────

// Path to the auto-generated file after `truffle compile`
const contractJsonPath = path.join(
  __dirname,
  "../../blockchain/build/contracts/Grievance.json"
);

// Check if the file exists — give a helpful error if not
if (!fs.existsSync(contractJsonPath)) {
  console.error(
    "❌ Grievance.json not found! Did you run `truffle compile` and `truffle migrate`?"
  );
  process.exit(1);
}

// Load and parse the JSON file
const GrievanceJSON = JSON.parse(fs.readFileSync(contractJsonPath, "utf8"));

// The ABI is the "interface" — it tells Web3.js what functions the contract has
const contractABI = GrievanceJSON.abi;

// ─────────────────────────────────────────────
// STEP 3 — Get the deployed contract address
// ─────────────────────────────────────────────

/**
 * The contract address is stored inside Grievance.json under "networks".
 * Truffle stores it as: networks[networkId].address
 *
 * We grab the LAST network entry because that's the most recently deployed one.
 * (Every time you `truffle migrate`, it may use a different network ID)
 */
const networkIds    = Object.keys(GrievanceJSON.networks);

if (networkIds.length === 0) {
  console.error(
    "❌ No deployed contract found in Grievance.json! Did you run `truffle migrate`?"
  );
  process.exit(1);
}

// Use Ganache network ID 1337 specifically
const ganacheNetworkId = "1337";
const contractAddress = GrievanceJSON.networks[ganacheNetworkId].address;

console.log(`✅ Grievance contract loaded at address: ${contractAddress}`);

// ─────────────────────────────────────────────
// STEP 4 — Create the contract instance
// ─────────────────────────────────────────────

// This is the object your routes will use to call contract functions
const grievanceContract = new web3.eth.Contract(contractABI, contractAddress);

// Export everything routes might need
module.exports = { web3, grievanceContract, contractAddress };